// This file has been generated by reducer-gen (@Stefan Pauka) written in 2020.
// DO NOT Change anything inside this file. Every time the generator is used, it will be overwritten.

import IState from "./state";
        
export const getSnackbarDefaultState = (): IState => ({
    appState: undefined,
    darkMode: false,
    snackbarDatas: [],
    isHeaderExpanded: false,
    loadingIndicators: [],
    globalLoadingIndicators: [],
    locale: null,
    feature: null,
    appBasePath: null,
  
});

export default getSnackbarDefaultState