// This file has been generated by reducer-gen (@Stefan Pauka) written in 2020.
// DO NOT Change anything inside this file. Every time the generator is used, it will be overwritten.

import { SnackbarReducerActions as RAs } from "./reducerActions/reducerActions.main.generated";
export { snackbarReducer } from "./reducer/reducer.main.generated";
export { SNACKBAR_ACTIONS } from "./actions/action.main.generated";
export { snackbarActionCreators } from "./actionCreators/actionCreators.main.generated";
export * from "./ReducerContext.main.generated";

export type SnackbarReducerActions = RAs 
