// This file has been generated by reducer-gen (@Stefan Pauka) written in 2020.
// DO NOT Change anything inside this file. Every time the generator is used, it will be overwritten.

import notificationsActionCreatorsBase from "./actionCreators.base.generated";
import notificationsActionCreatorsExtended from "./actionCreators.extended";

export const notificationsActionCreators = { ...notificationsActionCreatorsBase, ...notificationsActionCreatorsExtended }

export default notificationsActionCreators