// This file has been generated by reducer-gen (@Stefan Pauka) written in 2020.
// DO NOT Change anything inside this file. Every time the generator is used, it will be overwritten.

import ConfirmData from "../../interfaces/ConfirmData";
import ReducerAction from "./../reducerActions/reducerActions.base.generated";
import actions from "./../actions/action.base.generated";

export const notificationsActionCreatorsBase = {
    setConfirmDatas: (nextConfirmDatas:  ConfirmData[]): ReducerAction => (
        {
            type: actions.NOTIFICATIONS_SET_CONFIRM_DATAS,
            next: nextConfirmDatas,
        }),        
}

export default notificationsActionCreatorsBase;
