// This file has been generated by reducer-gen (@Stefan Pauka) written in 2020.
// DO NOT Change anything inside this file. Every time the generator is used, it will be overwritten.

import SnackbarReducerActionsBase, { isSnackbarReducerActionsBase } from "./reducerActions.base.generated";
import SnackbarReducerActionsExtended, { isSnackbarReducerActionsExtended } from "./reducerActions.extended";

export type SnackbarReducerActions = SnackbarReducerActionsBase | SnackbarReducerActionsExtended;

export const isSnackbarReducerActions = (item: any): item is SnackbarReducerActions => {
    return isSnackbarReducerActionsBase(item) || isSnackbarReducerActionsExtended(item);
}

export default SnackbarReducerActions;
