// This file has been generated by reducer-gen (@Stefan Pauka) written in 2020.
// DO NOT Change anything inside this file. Every time the generator is used, it will be overwritten.

import { SnackbarData } from "../../interfaces/SnackbarData";
import actions from "./../actions/action.base.generated";
        
export type SnackbarReducerActionsBase = { type: actions } & (
   | {
        type: actions.SNACKBAR_SET_SNACKBAR_DATAS;
        next:  SnackbarData[];
    }
);

export const isSnackbarReducerActionsBase = (item: any): item is SnackbarReducerActionsBase => {
    if (!item) { return false; }
    if (typeof item === "object") {
        const { type } = item;

        return typeof type === "string" && actions.hasOwnProperty(type);
    }
    return false;
}

export default SnackbarReducerActionsBase