// This file has been generated by reducer-gen (@Stefan Pauka) written in 2020.
// DO NOT Change anything inside this file. Every time the generator is used, it will be overwritten.

import { NotificationsReducerActions as RAs } from "./reducerActions/reducerActions.main.generated";
export { notificationsReducer } from "./reducer/reducer.main.generated";
export { NOTIFICATIONS_ACTIONS } from "./actions/action.main.generated";
export { notificationsActionCreators } from "./actionCreators/actionCreators.main.generated";
export * from "./ReducerContext.main.generated";

export type NotificationsReducerActions = RAs 
