// This file has been generated by reducer-gen (@Stefan Pauka) written in 2020.

import ConfirmData from "../../interfaces/ConfirmData";
import extenededActions from "./../actions/action.extended";

/**
 * You may add here extending reducer actions for this features reducer
 */

export type NotificationsReducerActionsExtended = { type: extenededActions } & (
  | {
      type: extenededActions.NOTIFICATIONS_ADD_CONFIRM_DATA;
      data: ConfirmData;
    }
  | {
      type: extenededActions.NOTIFICATIONS_REMOVE_CONFIRM_DATA;
      data: ConfirmData;
    }
  | {
      type: extenededActions.NOTIFICATIONS_UPDATE_CONFIRM_DATA;
      old: ConfirmData;
      next: ConfirmData;
    } // replace by following template for every extenededActions
  //    | {
  //        type: extenededActions["[action name]"];
  //        /* [additional payload like : next:  boolean;]*/
  //    }
);

export const isNotificationsReducerActionsExtended = (
  item: any
): item is NotificationsReducerActionsExtended => {
  if (!item) {
    return false;
  }
  if (typeof item === "object") {
    const { type } = item;

    return typeof type === "string" && extenededActions.hasOwnProperty(type);
  }
  return false;
};

export default NotificationsReducerActionsExtended;
