// This file has been generated by reducer-gen (@Stefan Pauka) written in 2020.
// DO NOT Change anything inside this file. Every time the generator is used, it will be overwritten.

import notificationsReducerBase from "./reducer.base.generated";
import notificationsReducerExtended from "./reducer.extended";
import { isNotificationsReducerActionsBase } from "./../reducerActions/reducerActions.base.generated";
import State from "./../state";
import getDefaultState from "./../defaultState.base.generated";
import NotificationsReducerActions from "./../reducerActions/reducerActions.main.generated";
        
export const notificationsReducer = (state: State = getDefaultState(), action:  NotificationsReducerActions): State => {
    // Note: Generator may be extended to inversify this order => Just talk to me ;)
    // return notificationsReducerExtended((isNotificationsReducerActionsBase(action) ? notificationsReducerBase(state, action) : state), action);
    
    return (isNotificationsReducerActionsBase(action) ? notificationsReducerBase(notificationsReducerExtended(state, action), action) : notificationsReducerExtended(state, action));
}

export default notificationsReducer;
