// This file has been generated by reducer-gen (@Stefan Pauka) written in 2020.
// DO NOT Change anything inside this file. Every time the generator is used, it will be overwritten.

import State from "./../state";
import getDefaultState from "./../defaultState.base.generated";
import ReducerAction from "./../reducerActions/reducerActions.base.generated";
import actions from "./../actions/action.base.generated";
            
const notificationsReducerBase = (state: State = getDefaultState(), action: ReducerAction): State => {
    switch (action.type) {
       case actions.NOTIFICATIONS_SET_CONFIRM_DATAS:
            return {
                ...state, 
                confirmDatas: action.next,
            };        
        default:
            return state; 
    }
}


export default notificationsReducerBase