// This file has been generated by reducer-gen (@Stefan Pauka) written in 2020.
// DO NOT Change anything inside this file. Every time the generator is used, it will be overwritten.

export enum NOTIFICATIONS_ACTIONS_BASE {
    NOTIFICATIONS_SET_CONFIRM_DATAS = "NOTIFICATIONS_SET_CONFIRM_DATAS",
}

export default NOTIFICATIONS_ACTIONS_BASE;
