// This file has been generated by reducer-gen (@Stefan Pauka) written in 2020.
// DO NOT Change anything inside this file. Every time the generator is used, it will be overwritten.

import NOTIFICATIONS_ACTIONS_BASE from "./action.base.generated";
import NOTIFICATIONS_ACTIONS_EXTENDED from "./action.extended";
        
export const NOTIFICATIONS_ACTIONS = { ...NOTIFICATIONS_ACTIONS_BASE, ...NOTIFICATIONS_ACTIONS_EXTENDED };

export default NOTIFICATIONS_ACTIONS