// This file has been generated by reducer-gen (@Stefan Pauka) written in 2020.
// DO NOT Change anything inside this file. Every time the generator is used, it will be overwritten.

import snackbarReducerBase from "./reducer.base.generated";
import snackbarReducerExtended from "./reducer.extended";
import { isSnackbarReducerActionsBase } from "./../reducerActions/reducerActions.base.generated";
import State from "./../state";
import getDefaultState from "./../defaultState.base.generated";
import SnackbarReducerActions from "./../reducerActions/reducerActions.main.generated";
        
export const snackbarReducer = (state: State = getDefaultState(), action:  SnackbarReducerActions): State => {
    // Note: Generator may be extended to inversify this order => Just talk to me ;)
    // return snackbarReducerExtended((isSnackbarReducerActionsBase(action) ? snackbarReducerBase(state, action) : state), action);
    
    return (isSnackbarReducerActionsBase(action) ? snackbarReducerBase(snackbarReducerExtended(state, action), action) : snackbarReducerExtended(state, action));
}

export default snackbarReducer;
