// This file has been generated by reducer-gen (@Stefan Pauka) written in 2020.
// DO NOT Change anything inside this file. Every time the generator is used, it will be overwritten.

import { SnackbarData } from "../../interfaces/SnackbarData";
import ReducerAction from "./../reducerActions/reducerActions.base.generated";
import actions from "./../actions/action.base.generated";

export const snackbarActionCreatorsBase = {
    setSnackbarDatas: (nextSnackbarDatas:  SnackbarData[]): ReducerAction => (
        {
            type: actions.SNACKBAR_SET_SNACKBAR_DATAS,
            next: nextSnackbarDatas,
        }),        
}

export default snackbarActionCreatorsBase;
