// This file has been generated by reducer-gen (@Stefan Pauka) written in 2020.
// DO NOT Change anything inside this file. Every time the generator is used, it will be overwritten.

import snackbarActionCreatorsBase from "./actionCreators.base.generated";
import snackbarActionCreatorsExtended from "./actionCreators.extended";

export const snackbarActionCreators = { ...snackbarActionCreatorsBase, ...snackbarActionCreatorsExtended }

export default snackbarActionCreators