// This file has been generated by reducer-gen (@Stefan Pauka) written in 2020.
// DO NOT Change anything inside this file. Every time the generator is used, it will be overwritten.

export enum SNACKBAR_ACTIONS_BASE {
    SNACKBAR_SET_SNACKBAR_DATAS = "SNACKBAR_SET_SNACKBAR_DATAS",
}

export default SNACKBAR_ACTIONS_BASE;
