// This file has been generated by reducer-gen (@Stefan Pauka) written in 2020.

export enum APP_ACTIONS_EXTENDED {
    // e.g. SET_IS_LOGGED_IN_EXT = "SET_IS_LOGGED_IN_EXT",
    ADD_SNACKBAR_DATA = "ADD_SNACKBAR_DATA",
    REMOVE_SNACKBAR_DATA = "REMOVE_SNACKBAR_DATA",
}

export default APP_ACTIONS_EXTENDED;
