// This file has been generated by reducer-gen (@Stefan Pauka) written in 2020.
// DO NOT Change anything inside this file. Every time the generator is used, it will be overwritten.

import SNACKBAR_ACTIONS_BASE from "./action.base.generated";
import SNACKBAR_ACTIONS_EXTENDED from "./action.extended";
        
export const SNACKBAR_ACTIONS = { ...SNACKBAR_ACTIONS_BASE, ...SNACKBAR_ACTIONS_EXTENDED };

export default SNACKBAR_ACTIONS